---

- name: Deploy Flask App
  hosts: FlaskServers
  tasks:
    - name: Ensure app directory exists
      file:
        path: /home/centos/FlaskWebApp/
        state: directory
      when: ansible_os_family == 'RedHat'

    - name: Ensure app directory exists
      file:
        path: /home/ubuntu/FlaskWebApp/
        state: directory
      when: ansible_os_family == 'Debian'

    - name: Copy Flask app files
      copy:
        src: /home/ubuntu/FlaskWebApp/app.py
        dest: /path/to/your/flask/app
        remote_src: yes
    
    - name: Install Flask dependencies
      pip:
        requirements: /path/to/your/flask/app/requirements.txt
        virtualenv: /path/to/your/flask/app/venv

    - name: Run Flask app
      command: /path/to/your/flask/app/venv/bin/python /path/to/your/flask/app/app.py
      async: 600
      poll: 0
...